[2025-03-21T19:58:45.216+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-21T19:58:45.407+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-21T19:58:45.409+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-03-21T19:58:45.572+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): ingest_account_dim> on 2025-03-20 00:00:00+00:00
[2025-03-21T19:58:45.586+0000] {standard_task_runner.py:57} INFO - Started process 937 to run task
[2025-03-21T19:58:45.598+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dimension_batch_ingestion', 'ingest_account_dim', 'scheduled__2025-03-20T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/loader_dag.py', '--cfg-path', '/tmp/tmpw_q31te5']
[2025-03-21T19:58:45.605+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask ingest_account_dim
[2025-03-21T19:58:45.777+0000] {task_command.py:415} INFO - Running <TaskInstance: dimension_batch_ingestion.ingest_account_dim scheduled__2025-03-20T00:00:00+00:00 [running]> on host c601b8b43588
[2025-03-21T19:58:47.459+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kebishaa' AIRFLOW_CTX_DAG_ID='dimension_batch_ingestion' AIRFLOW_CTX_TASK_ID='ingest_account_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T00:00:00+00:00'
[2025-03-21T19:58:48.404+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-21T19:58:48.411+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -X POST -F file=@/opt/***/account_dim_large_data.csv -H "Content-Type: multipart/form-data" "http://pinot-controller:9000/ingestFromFile?tableNameWithType=account_dim_OFFLINE&batchConfigMapStr=%7B%22inputFormat%22%3A%22csv%22%2C%22recordReader.prop.delimiter%22%3A%22%2C%22%7D"']
[2025-03-21T19:58:48.645+0000] {subprocess.py:86} INFO - Output:
[2025-03-21T19:58:56.447+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2025-03-21T19:58:56.449+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2025-03-21T19:58:56.731+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[2025-03-21T19:58:56.734+0000] {subprocess.py:93} INFO - curl: (7) Failed to connect to pinot-controller port 9000: Connection refused
[2025-03-21T19:58:57.256+0000] {subprocess.py:97} INFO - Command exited with return code 7
[2025-03-21T19:58:57.292+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 7.
[2025-03-21T19:58:57.381+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dimension_batch_ingestion, task_id=ingest_account_dim, execution_date=20250320T000000, start_date=20250321T195845, end_date=20250321T195857
[2025-03-21T19:58:57.895+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task ingest_account_dim (Bash command failed. The command returned a non-zero exit code 7.; 937)
[2025-03-21T19:58:57.939+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-21T19:58:58.422+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
